# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "page-bars"
client_id = "9fbe80571b70c7c7924782e91c279e55"
application_url = "https://clinical-litigation-driven-arts.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,write_price_rules,read_orders,write_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://clinical-litigation-driven-arts.trycloudflare.com/auth/callback",
  "https://clinical-litigation-driven-arts.trycloudflare.com/auth/shopify/callback",
  "https://clinical-litigation-driven-arts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "neon-customizer-dropshipping-app.myshopify.com"
